version: '3.8'
services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-trading_bot}
    networks:
      - execution-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: execution-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - execution-network
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"  # AMQP protocol port
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672" # Management UI

  # Redis Cache
  cache:
    image: redis:7-alpine
    container_name: execution-redis
    restart: always
    command: redis-server
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - execution-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis-data:

networks:
  execution-network:
    driver: bridge