version: '3.8'
services:
  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: monitoring-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - monitoring-network
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"  # AMQP protocol port
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672" # Management UI

  # Redis Cache
  cache:
    image: redis:7-alpine
    container_name: monitoring-redis
    restart: always
    command: redis-server
    volumes:
      - redis-data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - monitoring-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:

networks:
  monitoring-network:
    driver: bridge